In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
train_df = pd.read_csv('train_Df64byy.csv')
test_df = pd.read_csv('test_YCcRUnU.csv')

In [3]:
train_df.head()

ID City_Code  Region_Code Accomodation_Type Reco_Insurance_Type  Upper_Age  \
0   1        C3         3213            Rented          Individual         36   
1   2        C5         1117             Owned               Joint         75   
2   3        C5         3732             Owned          Individual         32   
3   4       C24         4378             Owned               Joint         52   
4   5        C8         2190            Rented          Individual         44   

   Lower_Age Is_Spouse Health Indicator Holding_Policy_Duration  \
0         36        No               X1                     14+   
1         22        No               X2                     NaN   
2         32        No              NaN                     1.0   
3         48        No               X1                     14+   
4         44        No               X2                     3.0   

   Holding_Policy_Type  Reco_Policy_Cat  Reco_Policy_Premium  Response  
0                  3.0               22              11628.0         0  
1                  NaN               22              30510.0         0  
2                  1.0               19               7450.0         1  
3                  3.0               19              17780.0         0  
4                  1.0               16              10404.0         0

In [4]:
test_df.head()

ID City_Code  Region_Code Accomodation_Type Reco_Insurance_Type  \
0  50883        C1          156             Owned          Individual   
1  50884        C4            7             Owned               Joint   
2  50885        C1          564            Rented          Individual   
3  50886        C3         1177            Rented          Individual   
4  50887        C1          951             Owned          Individual   

   Upper_Age  Lower_Age Is_Spouse Health Indicator Holding_Policy_Duration  \
0         30         30        No              NaN                     6.0   
1         69         68       Yes               X1                     3.0   
2         28         28        No               X3                     2.0   
3         23         23        No               X3                     3.0   
4         75         75        No               X3                     NaN   

   Holding_Policy_Type  Reco_Policy_Cat  Reco_Policy_Premium  
0                  3.0                5              11934.0  
1                  3.0               18              32204.8  
2                  4.0               17               9240.0  
3                  3.0               18               9086.0  
4                  NaN                5              22534.0

In [5]:
# Categorical Data
train_categorical = train_df.select_dtypes(include=[np.object])
obj_col = [col for col in train_df.keys() if train_df[col].dtype=='O']
print('Categorical Data of train data -->', train_categorical.shape[1],'\n',  obj_col)
print('*****************************************************************************')

# Numerical Data
train_numerical = train_df.select_dtypes(include=[np.int64])
print('Numerical Data of train data -->', train_numerical.shape[1])

Categorical Data of train data --> 6 
 ['City_Code', 'Accomodation_Type', 'Reco_Insurance_Type', 'Is_Spouse', 'Health Indicator', 'Holding_Policy_Duration']
*****************************************************************************
Numerical Data of train data --> 6


In [6]:
# Sum of null values in train data
train_df.isnull().sum()

ID                             0
City_Code                      0
Region_Code                    0
Accomodation_Type              0
Reco_Insurance_Type            0
Upper_Age                      0
Lower_Age                      0
Is_Spouse                      0
Health Indicator           11691
Holding_Policy_Duration    20251
Holding_Policy_Type        20251
Reco_Policy_Cat                0
Reco_Policy_Premium            0
Response                       0
dtype: int64

In [7]:
# Categorical Data
test_categorical = test_df.select_dtypes(include=[np.object])
obj_col_test = [col for col in test_df.keys() if test_df[col].dtype=='O']
print('Categorical Data of test data -->', test_categorical.shape[1],'\n',  obj_col_test)
print('*****************************************************************************')

# Numerical Data
test_numerical = test_df.select_dtypes(include=[np.int64])
print('Numerical Data of test data -->', test_numerical.shape[1])

Categorical Data of test data --> 6 
 ['City_Code', 'Accomodation_Type', 'Reco_Insurance_Type', 'Is_Spouse', 'Health Indicator', 'Holding_Policy_Duration']
*****************************************************************************
Numerical Data of test data --> 5


In [8]:
# Sum of null values in test data
test_df.isnull().sum()

ID                            0
City_Code                     0
Region_Code                   0
Accomodation_Type             0
Reco_Insurance_Type           0
Upper_Age                     0
Lower_Age                     0
Is_Spouse                     0
Health Indicator           5027
Holding_Policy_Duration    8603
Holding_Policy_Type        8603
Reco_Policy_Cat               0
Reco_Policy_Premium           0
dtype: int64

In [9]:
def imp(col):
    train_df['Health Indicator']
  
    if col=='X1':
        return 1
    elif col=='X2':
        return 2
    elif col=='X3':
        return 3
    elif col=='X4':
        return 4
    elif col=='X5':
        return 5
    elif col=='X6':
        return 6
    elif col=='X7':
        return 7
    elif col=='X8':
        return 8
    elif col=='X9':
        return 9
    else:
        return np.nan

In [10]:
#train Data 
train_df['Health Indicator'] = train_df['Health Indicator'].apply(imp).astype(float)
train_df['Health Indicator'] = train_df['Health Indicator'].replace('nan',np.nan)
# Test Data
test_df['Health Indicator'] = test_df['Health Indicator'].apply(imp).astype(float)
test_df['Health Indicator'] = test_df['Health Indicator'].replace('nan',np.nan)

In [11]:
train_df['Health Indicator'].unique()

array([ 1.,  2., nan,  4.,  3.,  6.,  5.,  8.,  7.,  9.])

In [12]:
train_df['Holding_Policy_Duration'] = train_df['Holding_Policy_Duration'].replace('14+','14')

test_df['Holding_Policy_Duration'] = test_df['Holding_Policy_Duration'].replace('14+','14')

In [13]:
test_df['Holding_Policy_Duration'].unique()

array(['6.0', '3.0', '2.0', nan, '14', '5.0', '1.0', '4.0', '12.0',
       '11.0', '7.0', '9.0', '13.0', '8.0', '14.0', '10.0'], dtype=object)

In [14]:
train_df['Holding_Policy_Type'].unique()

array([ 3., nan,  1.,  4.,  2.])

In [15]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
train_df['City_Code'] = encoder.fit_transform(train_df['City_Code'])
test_df['City_Code'] = encoder.fit_transform(test_df['City_Code'])

In [16]:
train_df['Accomodation_Type'] = pd.get_dummies(train_df['Accomodation_Type'],drop_first=False)
train_df['Reco_Insurance_Type'] = pd.get_dummies(train_df['Reco_Insurance_Type'],drop_first=False)
train_df['Is_Spouse'] = pd.get_dummies(train_df['Is_Spouse'],drop_first=False)

In [17]:
test_df['Accomodation_Type'] = pd.get_dummies(test_df['Accomodation_Type'],drop_first=False)
test_df['Reco_Insurance_Type'] = pd.get_dummies(test_df['Reco_Insurance_Type'],drop_first=False)
test_df['Is_Spouse'] = pd.get_dummies(test_df['Is_Spouse'],drop_first=False)

In [19]:
test_df

ID  City_Code  Region_Code  Accomodation_Type  Reco_Insurance_Type  \
0      50883          0          156                  1                    1   
1      50884         30            7                  1                    0   
2      50885          0          564                  0                    1   
3      50886         22         1177                  0                    1   
4      50887          0          951                  1                    1   
...      ...        ...          ...                ...                  ...   
21800  72683         22         1044                  1                    1   
21801  72684         30          266                  1                    1   
21802  72685          3         2470                  1                    1   
21803  72686          1         1676                  0                    1   
21804  72687         11         3617                  1                    1   

       Upper_Age  Lower_Age  Is_Spouse  Health Indicator  \
0             30         30          1               NaN   
1             69         68          0               1.0   
2             28         28          1               3.0   
3             23         23          1               3.0   
4             75         75          1               3.0   
...          ...        ...        ...               ...   
21800         45         45          1               1.0   
21801         59         59          1               5.0   
21802         74         74          1               3.0   
21803         25         25          1               4.0   
21804         73         73          1               2.0   

      Holding_Policy_Duration  Holding_Policy_Type  Reco_Policy_Cat  \
0                         6.0                  3.0                5   
1                         3.0                  3.0               18   
2                         2.0                  4.0               17   
3                         3.0                  3.0               18   
4                         NaN                  NaN                5   
...                       ...                  ...              ...   
21800                     4.0                  1.0               18   
21801                     6.0                  3.0               18   
21802                     NaN                  NaN                1   
21803                     3.0                  1.0               19   
21804                      14                  2.0                3   

       Reco_Policy_Premium  
0                  11934.0  
1                  32204.8  
2                   9240.0  
3                   9086.0  
4                  22534.0  
...                    ...  
21800              15884.0  
21801              21390.0  
21802              17836.0  
21803              11568.0  
21804              23040.0  

[21805 rows x 13 columns]

In [20]:
key_tr = train_df.keys()
key_ts = test_df.keys()

In [21]:
from sklearn.impute import KNNImputer
knnimputer = KNNImputer(n_neighbors=5)
train_df = knnimputer.fit_transform(train_df)
test_df = knnimputer.fit_transform(test_df)

In [22]:
train_df=pd.DataFrame(train_df,columns=key_tr)
test_df=pd.DataFrame(test_df,columns=key_ts)

In [23]:
train_df['Health Indicator'].unique()

array([1. , 2. , 3.2, 2.8, 4. , 3. , 2.6, 6. , 5. , 1.4, 1.8, 3.4, 2.2,
       4.8, 1.6, 2.4, 3.6, 1.2, 3.8, 8. , 7. , 4.2, 4.6, 4.4, 9. , 5.2,
       5.8])

In [24]:
train_df['Health Indicator'] = np.ceil(train_df['Health Indicator'])

In [25]:
train_df['Health Indicator'].unique()

array([1., 2., 4., 3., 6., 5., 8., 7., 9.])

In [26]:
X=train_df.drop(['Response', 'ID', 'City_Code', 'Region_Code'],axis=1)
y=train_df['Response']

In [27]:
X.head(1)

Accomodation_Type  Reco_Insurance_Type  Upper_Age  Lower_Age  Is_Spouse  \
0                0.0                  1.0       36.0       36.0        1.0   

   Health Indicator  Holding_Policy_Duration  Holding_Policy_Type  \
0               1.0                     14.0                  3.0   

   Reco_Policy_Cat  Reco_Policy_Premium  
0             22.0              11628.0

In [28]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)
test_df = scaler.fit_transform(test_df)

In [29]:
X_key = key_tr.drop(['ID', 'City_Code', 'Region_Code', 'Response'])

In [30]:
X=pd.DataFrame(X,columns=X_key)
test_df=pd.DataFrame(test_df,columns=key_ts)

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =101)

In [32]:
from imblearn.over_sampling import SMOTE
smote = SMOTE()
X_train_smote, y_train_smote = smote.fit_sample(X_train,y_train)

In [33]:
X_train_smote.shape

(54012, 10)

In [34]:
from sklearn.linear_model import LogisticRegression
log_model = LogisticRegression()
log_model.fit(X_train_smote, y_train_smote)
prediction_x = log_model.predict(X_test)
prediction_x

array([0., 0., 1., ..., 0., 1., 1.])

In [35]:
from sklearn.metrics import roc_auc_score
roc_score = roc_auc_score(y_test, prediction_x)
roc_score

0.5380998524317553

In [37]:
from collections import Counter
print('before SMOTE', Counter(y_train))
print('after SMOTE', Counter(y_train_smote))

before SMOTE Counter({0.0: 27006, 1.0: 8611})
after SMOTE Counter({0.0: 27006, 1.0: 27006})


In [36]:
submission = pd.read_csv('sample_submission_QrCyCoT.csv')
final_predictions = log_model.predict(test_df.drop(['ID', 'City_Code', 'Region_Code'],axis=1))
submission['Response'] = final_predictions
#only positive predictions for the target variable

submission.to_csv('smote_log.csv', index=False)